name: Weekly Crypto Model, Plot & Log Update

on:
  schedule:
    - cron: "0 2 * * 0"  # Every Sunday at 2 AM UTC
  workflow_dispatch:

permissions:
  contents: write  # Needed to push changes back

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run weekly trainer
        run: python weekly_trainer.py

      - name: Commit and push updated files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add models/ plots/ logs/
          git commit -m "Weekly update: models, plots & logs [skip ci]" || echo "No changes to commit"
          git push
